### ISSUE TITLE
cant work in my terminal :(

### ISSUE THREAD

**Issue by leaningzzZ** [Vincent0700/vincent0700-cli#2]

**Comment by Vincent0700** [comment]
What's your operation system?

**Comment by leaningzzZ** [comment]
> What's your operation system?

macOS 
node :  v10.21.0

**Comment by leaningzzZ** [comment]
> > What's your operation system?
> 
> macOS
> node : v10.21.0



![image](https://user-images.githubusercontent.com/38056961/106749142-1ed3f400-6661-11eb-90a5-1c7c4d62bd23.png)
![image](https://user-images.githubusercontent.com/38056961/106749174-27c4c580-6661-11eb-8de7-5bf91616f6c0.png)

**Comment by Vincent0700** [comment]
Node 升级到 12 或以上试试，我试了下 Node 10 确实无法展示，我还在看是什么原因导致的。

**Comment by leaningzzZ** [comment]
> Node 升级到 12 或以上试试，我试了下 Node 10 确实无法展示，我还在看是什么原因导致的。

12.20.1正常，膜拜大佬
