### ISSUE TITLE
how to do this?

### ISSUE THREAD

**Issue by devcui** [Vincent0700/vincent0700-cli#3]
构想思路，实现思路？

这也太炫酷了

**Comment by Vincent0700** [comment]
跟渲染 ascii 像画的原理差不多，有兴趣可以一起交流 ~

**Comment by devcui** [comment]
好呀好呀，有时间我先模仿一个cli出来
PS: 个人博客 是自己写的还是用什么第三方搞的，好漂亮，俺也想整一个

**Comment by devcui** [comment]
PS .dat 桢文件实质上是什么？现在卡在这里，没有数据源  🥺🥺🥺

**Comment by Vincent0700** [comment]
为了压缩体积并且不用把图片读写的 runtime 打到包里，我自己定义了一种二进制格式， 简单来说就是 8bit 调色板 + 颜色 index。

**Comment by Vincent0700** [comment]
> 好呀好呀，有时间我先模仿一个cli出来
> PS: 个人博客 是自己写的还是用什么第三方搞的，好漂亮，俺也想整一个

[Hexo](https://hexo.io)

**Comment by devcui** [comment]
感谢姐姐带我进入了terminal新世界大门😂
效仿这个仓，我要尝试一下解析png到terminal上:    https://github.com/devcui/devcui-cli
issues先关闭啦
PS: 可否有幸成为你的微信好友呐，有问题可以直接探讨 QR:  https://static.eiyouhe.com/mywechat.jpg

**Comment by devcui** [comment]
https://github.com/devcui/garlic-turtle
算是实现了半个吧。。。哈哈哈哈哈
